growth_key: mu
START_tRNA: []
rna_components: []
feature_types:
- CDS
- rRNA
- tRNA
- ncRNA
- tmRNA
trna_misacylation: {}
knockouts: []
genome_mods: {}
peptide_release_factors:
  UAG: g.23654.CDS.556-MONOMER
  UGA: g.23654.CDS.262-MONOMER
  UAA: generic_RF
complex_cofactors:
  fes_transfers:
  - g.23654.CDS.3302-MONOMER
  fes_chaperones: {}
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_NiFe_cofactor_c: []
lipid_modifications: []
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- biomass516
- FMETTRS
- ATPM
ME-Model-ID: Brachybacterium_paraconglomeratum_LC44-ME
m-model-path: ./me-models/Brachybacterium_paraconglomeratum_LC44//building_data/m_model_modified.json
genbank-path: ./me-models/Brachybacterium_paraconglomeratum_LC44//building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: ./me-models/Brachybacterium_paraconglomeratum_LC44/Brachybacterium_paraconglomeratum_LC44.xlsx
df_TranscriptionalUnits: ./me-models/Brachybacterium_paraconglomeratum_LC44//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ''
df_matrix_subrxn_stoich: ''
df_metadata_orphan_rxns: ''
df_metadata_metabolites: ''
log_directory: ./me-models/Brachybacterium_paraconglomeratum_LC44/
out_directory: ./me-models/Brachybacterium_paraconglomeratum_LC44/
dev_reference: false
include_pseudo_genes: true
add_lipoproteins: false
estimate_keffs: true
blast_threads: 1
run_bbh_blast: false
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- g.23654.CDS.1094-MONOMER
other_lipids:
- g.23654.CDS.2494-MONOMER
default_sigma_factor: g.23654.CDS.123-MONOMER
rna_polymerases:
  RNAP_g23654CDS123MONOMER:
    sigma_factor: g.23654.CDS.123-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_g23654CDS545MONOMER:
    sigma_factor: g.23654.CDS.545-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_g23654CDS1734MONOMER:
    sigma_factor: g.23654.CDS.1734-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_g23654CDS3214MONOMER:
    sigma_factor: g.23654.CDS.3214-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
lipoprotein_precursors:
  MetQ: g.23654.CDS.1484
ngam: 1.0
gam: 40.0
translocation_multipliers:
  g.23654.CDS.3246-MONOMER: {}
amino_acid_trna_synthetase:
  ala__L_c: g.23654.CDS.2525-MONOMER
  arg__L_c: g.23654.CDS.18-MONOMER
  asn__L_c: CPLX_dummy
  asp__L_c: g.23654.CDS.3083-MONOMER
  cys__L_c: g.23654.CDS.2437-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: generic_glu_ligase
  gly_c: g.23654.CDS.2070-MONOMER
  his__L_c: g.23654.CDS.3229-MONOMER
  ile__L_c: g.23654.CDS.2610-MONOMER
  leu__L_c: g.23654.CDS.1782-MONOMER
  lys__L_c: g.23654.CDS.2260-MONOMER
  met__L_c: g.23654.CDS.2650-MONOMER
  phe__L_c: generic_phe_ligase
  pro__L_c: g.23654.CDS.2259-MONOMER
  ser__L_c: g.23654.CDS.528-MONOMER
  thr__L_c: g.23654.CDS.3032-MONOMER
  trp__L_c: g.23654.CDS.1810-MONOMER
  tyr__L_c: g.23654.CDS.1917-MONOMER
  val__L_c: g.23654.CDS.2523-MONOMER
braun's_lipoproteins: []
