growth_key: mu
START_tRNA: []
rna_components: []
feature_types:
- CDS
- rRNA
- tRNA
- ncRNA
- tmRNA
trna_misacylation: {}
knockouts: []
genome_mods: {}
peptide_release_factors:
  UAG: 6x7.58860.peg.842-MONOMER
  UGA: 6x7.58860.peg.320-MONOMER
  UAA: generic_RF
complex_cofactors:
  fes_transfers:
  - CPLX_dummy
  fes_chaperones: {}
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_NiFe_cofactor_c: []
lipid_modifications: []
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- biomass345
- FMETTRS
- ATPM
ME-Model-ID: Bacteroides_fragilis_NCTC_9343-ME
m-model-path: ./me-models/Bacteroides_fragilis_NCTC_9343//building_data/m_model_modified.json
genbank-path: ./me-models/Bacteroides_fragilis_NCTC_9343//building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: ./me-models/Bacteroides_fragilis_NCTC_9343/Bacteroides_fragilis_NCTC_9343.xlsx
df_TranscriptionalUnits: ./me-models/Bacteroides_fragilis_NCTC_9343//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ''
df_matrix_subrxn_stoich: ''
df_metadata_orphan_rxns: ''
df_metadata_metabolites: ''
log_directory: ./me-models/Bacteroides_fragilis_NCTC_9343/
out_directory: ./me-models/Bacteroides_fragilis_NCTC_9343/
dev_reference: false
include_pseudo_genes: true
add_lipoproteins: false
estimate_keffs: true
blast_threads: 1
run_bbh_blast: false
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- 6x7.58860.peg.4591-MONOMER
other_lipids: []
default_sigma_factor: 6x7.58860.peg.200-MONOMER
rna_polymerases:
  RNAP_6x758860peg200MONOMER:
    sigma_factor: 6x7.58860.peg.200-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg231MONOMER:
    sigma_factor: 6x7.58860.peg.231-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg263MONOMER:
    sigma_factor: 6x7.58860.peg.263-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg504MONOMER:
    sigma_factor: 6x7.58860.peg.504-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg536MONOMER:
    sigma_factor: 6x7.58860.peg.536-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg571MONOMER:
    sigma_factor: 6x7.58860.peg.571-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg690MONOMER:
    sigma_factor: 6x7.58860.peg.690-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg879MONOMER:
    sigma_factor: 6x7.58860.peg.879-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg923MONOMER:
    sigma_factor: 6x7.58860.peg.923-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg973MONOMER:
    sigma_factor: 6x7.58860.peg.973-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg982MONOMER:
    sigma_factor: 6x7.58860.peg.982-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg988MONOMER:
    sigma_factor: 6x7.58860.peg.988-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1177MONOMER:
    sigma_factor: 6x7.58860.peg.1177-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1199MONOMER:
    sigma_factor: 6x7.58860.peg.1199-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1307MONOMER:
    sigma_factor: 6x7.58860.peg.1307-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1319MONOMER:
    sigma_factor: 6x7.58860.peg.1319-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1388MONOMER:
    sigma_factor: 6x7.58860.peg.1388-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1395MONOMER:
    sigma_factor: 6x7.58860.peg.1395-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1405MONOMER:
    sigma_factor: 6x7.58860.peg.1405-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1640MONOMER:
    sigma_factor: 6x7.58860.peg.1640-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1833MONOMER:
    sigma_factor: 6x7.58860.peg.1833-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1975MONOMER:
    sigma_factor: 6x7.58860.peg.1975-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1986MONOMER:
    sigma_factor: 6x7.58860.peg.1986-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg1993MONOMER:
    sigma_factor: 6x7.58860.peg.1993-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3014MONOMER:
    sigma_factor: 6x7.58860.peg.3014-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3053MONOMER:
    sigma_factor: 6x7.58860.peg.3053-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3086MONOMER:
    sigma_factor: 6x7.58860.peg.3086-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3218MONOMER:
    sigma_factor: 6x7.58860.peg.3218-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3349MONOMER:
    sigma_factor: 6x7.58860.peg.3349-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3370MONOMER:
    sigma_factor: 6x7.58860.peg.3370-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3545MONOMER:
    sigma_factor: 6x7.58860.peg.3545-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3571MONOMER:
    sigma_factor: 6x7.58860.peg.3571-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3689MONOMER:
    sigma_factor: 6x7.58860.peg.3689-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3742MONOMER:
    sigma_factor: 6x7.58860.peg.3742-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3750MONOMER:
    sigma_factor: 6x7.58860.peg.3750-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3817MONOMER:
    sigma_factor: 6x7.58860.peg.3817-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3908MONOMER:
    sigma_factor: 6x7.58860.peg.3908-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3926MONOMER:
    sigma_factor: 6x7.58860.peg.3926-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg3938MONOMER:
    sigma_factor: 6x7.58860.peg.3938-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg4341MONOMER:
    sigma_factor: 6x7.58860.peg.4341-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg4375MONOMER:
    sigma_factor: 6x7.58860.peg.4375-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg4496MONOMER:
    sigma_factor: 6x7.58860.peg.4496-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_6x758860peg4581MONOMER:
    sigma_factor: 6x7.58860.peg.4581-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
lipoprotein_precursors:
  AcrE: 6x7.58860.peg.3056
  BamB: 6x7.58860.peg.377
  CusC: 6x7.58860.peg.154
ngam: 1.0
gam: 40.0
translocation_multipliers:
  6x7.58860.peg.2705-MONOMER: {}
amino_acid_trna_synthetase:
  ala__L_c: 6x7.58860.peg.694-MONOMER
  arg__L_c: 6x7.58860.peg.4442-MONOMER
  asn__L_c: 6x7.58860.peg.3970-MONOMER
  asp__L_c: 6x7.58860.peg.2529-MONOMER
  cys__L_c: 6x7.58860.peg.162-MONOMER
  gln__L_c: 6x7.58860.peg.2865-MONOMER
  glu__L_c: 6x7.58860.peg.4221-MONOMER
  gly_c: 6x7.58860.peg.355-MONOMER
  his__L_c: 6x7.58860.peg.3380-MONOMER
  ile__L_c: 6x7.58860.peg.2426-MONOMER
  leu__L_c: 6x7.58860.peg.4595-MONOMER
  lys__L_c: 6x7.58860.peg.3772-MONOMER
  met__L_c: CPLX_dummy
  phe__L_c: generic_phe_ligase
  pro__L_c: 6x7.58860.peg.2586-MONOMER
  ser__L_c: 6x7.58860.peg.938-MONOMER
  thr__L_c: 6x7.58860.peg.1687-MONOMER
  trp__L_c: 6x7.58860.peg.3991-MONOMER
  tyr__L_c: 6x7.58860.peg.78-MONOMER
  val__L_c: 6x7.58860.peg.979-MONOMER
braun's_lipoproteins: []
