growth_key: mu
START_tRNA: []
rna_components: []
feature_types:
- CDS
- rRNA
- tRNA
- ncRNA
- tmRNA
trna_misacylation: {}
knockouts: []
genome_mods: {}
peptide_release_factors:
  UAG: g.26890.CDS.339-MONOMER
  UGA: g.26890.CDS.1349-MONOMER
  UAA: generic_RF
complex_cofactors:
  fes_transfers:
  - CPLX_dummy
  fes_chaperones: {}
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_NiFe_cofactor_c: []
lipid_modifications: []
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- biomass066
- FMETTRS
- ATPM
ME-Model-ID: Filifactor_alocis_ATCC_35896-ME
m-model-path: ./me-models/Filifactor_alocis_ATCC_35896//building_data/m_model_modified.json
genbank-path: ./me-models/Filifactor_alocis_ATCC_35896//building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: ./me-models/Filifactor_alocis_ATCC_35896/Filifactor_alocis_ATCC_35896.xlsx
df_TranscriptionalUnits: ./me-models/Filifactor_alocis_ATCC_35896//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ''
df_matrix_subrxn_stoich: ''
df_metadata_orphan_rxns: ''
df_metadata_metabolites: ''
log_directory: ./me-models/Filifactor_alocis_ATCC_35896/
out_directory: ./me-models/Filifactor_alocis_ATCC_35896/
dev_reference: false
include_pseudo_genes: true
add_lipoproteins: false
estimate_keffs: true
blast_threads: 1
run_bbh_blast: false
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- g.26890.CDS.596-MONOMER
- g.26890.CDS.600-MONOMER
other_lipids: []
default_sigma_factor: g.26890.CDS.27-MONOMER
rna_polymerases:
  RNAP_g26890CDS27MONOMER:
    sigma_factor: g.26890.CDS.27-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_g26890CDS128MONOMER:
    sigma_factor: g.26890.CDS.128-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_g26890CDS368MONOMER:
    sigma_factor: g.26890.CDS.368-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_g26890CDS1610MONOMER:
    sigma_factor: g.26890.CDS.1610-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
lipoprotein_precursors:
  MetQ: g.26890.CDS.486
  MltC: g.26890.CDS.1301
ngam: 1.0
gam: 41.257
translocation_multipliers:
  g.26890.CDS.1321-MONOMER:
    g.26890.CDS.74: 2.0
amino_acid_trna_synthetase:
  ala__L_c: g.26890.CDS.736-MONOMER
  arg__L_c: g.26890.CDS.203-MONOMER
  asn__L_c: g.26890.CDS.213-MONOMER
  asp__L_c: g.26890.CDS.292-MONOMER
  cys__L_c: g.26890.CDS.590-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: g.26890.CDS.915-MONOMER
  gly_c: g.26890.CDS.1333-MONOMER
  his__L_c: g.26890.CDS.1609-MONOMER
  ile__L_c: g.26890.CDS.1307-MONOMER
  leu__L_c: g.26890.CDS.273-MONOMER
  lys__L_c: g.26890.CDS.638-MONOMER
  met__L_c: g.26890.CDS.272-MONOMER
  phe__L_c: generic_phe_ligase
  pro__L_c: g.26890.CDS.897-MONOMER
  ser__L_c: g.26890.CDS.211-MONOMER
  thr__L_c: g.26890.CDS.1619-MONOMER
  trp__L_c: g.26890.CDS.805-MONOMER
  tyr__L_c: g.26890.CDS.234-MONOMER
  val__L_c: g.26890.CDS.707-MONOMER
braun's_lipoproteins: []
