growth_key: mu
START_tRNA: []
rna_components: []
feature_types:
- CDS
- rRNA
- tRNA
- ncRNA
- tmRNA
trna_misacylation: {}
knockouts: []
genome_mods: {}
peptide_release_factors:
  UAG: 435591.18.peg.2136-MONOMER
  UGA: 435591.18.peg.2788-MONOMER
  UAA: generic_RF
complex_cofactors:
  fes_transfers:
  - CPLX_dummy
  fes_chaperones: {}
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_NiFe_cofactor_c: []
lipid_modifications: []
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- biomass345
- FMETTRS
- ATPM
ME-Model-ID: Parabacteroides_distasonis_ATCC_8503-ME
m-model-path: ./me-models/Parabacteroides_distasonis_ATCC_8503//building_data/m_model_modified.json
genbank-path: ./me-models/Parabacteroides_distasonis_ATCC_8503//building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: ./me-models/Parabacteroides_distasonis_ATCC_8503/Parabacteroides_distasonis_ATCC_8503.xlsx
df_TranscriptionalUnits: ./me-models/Parabacteroides_distasonis_ATCC_8503//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ''
df_matrix_subrxn_stoich: ''
df_metadata_orphan_rxns: ''
df_metadata_metabolites: ''
log_directory: ./me-models/Parabacteroides_distasonis_ATCC_8503/
out_directory: ./me-models/Parabacteroides_distasonis_ATCC_8503/
dev_reference: false
include_pseudo_genes: true
add_lipoproteins: false
estimate_keffs: true
blast_threads: 1
run_bbh_blast: false
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- 435591.18.peg.3634-MONOMER
other_lipids: []
default_sigma_factor: 435591.18.peg.233-MONOMER
rna_polymerases:
  RNAP_43559118peg233MONOMER:
    sigma_factor: 435591.18.peg.233-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg404MONOMER:
    sigma_factor: 435591.18.peg.404-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg525MONOMER:
    sigma_factor: 435591.18.peg.525-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg595MONOMER:
    sigma_factor: 435591.18.peg.595-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg1332MONOMER:
    sigma_factor: 435591.18.peg.1332-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg1679MONOMER:
    sigma_factor: 435591.18.peg.1679-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg1721MONOMER:
    sigma_factor: 435591.18.peg.1721-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg1727MONOMER:
    sigma_factor: 435591.18.peg.1727-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg1738MONOMER:
    sigma_factor: 435591.18.peg.1738-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg1960MONOMER:
    sigma_factor: 435591.18.peg.1960-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2106MONOMER:
    sigma_factor: 435591.18.peg.2106-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2354MONOMER:
    sigma_factor: 435591.18.peg.2354-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2361MONOMER:
    sigma_factor: 435591.18.peg.2361-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2373MONOMER:
    sigma_factor: 435591.18.peg.2373-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2515MONOMER:
    sigma_factor: 435591.18.peg.2515-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2652MONOMER:
    sigma_factor: 435591.18.peg.2652-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2675MONOMER:
    sigma_factor: 435591.18.peg.2675-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2679MONOMER:
    sigma_factor: 435591.18.peg.2679-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg2892MONOMER:
    sigma_factor: 435591.18.peg.2892-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3030MONOMER:
    sigma_factor: 435591.18.peg.3030-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3148MONOMER:
    sigma_factor: 435591.18.peg.3148-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3157MONOMER:
    sigma_factor: 435591.18.peg.3157-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3168MONOMER:
    sigma_factor: 435591.18.peg.3168-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3176MONOMER:
    sigma_factor: 435591.18.peg.3176-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3215MONOMER:
    sigma_factor: 435591.18.peg.3215-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3517MONOMER:
    sigma_factor: 435591.18.peg.3517-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3525MONOMER:
    sigma_factor: 435591.18.peg.3525-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3864MONOMER:
    sigma_factor: 435591.18.peg.3864-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg3922MONOMER:
    sigma_factor: 435591.18.peg.3922-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_43559118peg4035MONOMER:
    sigma_factor: 435591.18.peg.4035-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
lipoprotein_precursors:
  CusC: 435591.18.peg.994
ngam: 1.0
gam: 40.0
translocation_multipliers:
  435591.18.peg.518-MONOMER: {}
amino_acid_trna_synthetase:
  ala__L_c: 435591.18.peg.2578-MONOMER
  arg__L_c: 435591.18.peg.3671-MONOMER
  asn__L_c: 435591.18.peg.3797-MONOMER
  asp__L_c: 435591.18.peg.1433-MONOMER
  cys__L_c: 435591.18.peg.2873-MONOMER
  gln__L_c: 435591.18.peg.1418-MONOMER
  glu__L_c: 435591.18.peg.2324-MONOMER
  gly_c: 435591.18.peg.3248-MONOMER
  his__L_c: 435591.18.peg.3860-MONOMER
  ile__L_c: 435591.18.peg.447-MONOMER
  leu__L_c: 435591.18.peg.3045-MONOMER
  lys__L_c: 435591.18.peg.146-MONOMER
  met__L_c: CPLX_dummy
  phe__L_c: generic_phe_ligase
  pro__L_c: 435591.18.peg.1012-MONOMER
  ser__L_c: 435591.18.peg.538-MONOMER
  thr__L_c: 435591.18.peg.664-MONOMER
  trp__L_c: 435591.18.peg.3516-MONOMER
  tyr__L_c: 435591.18.peg.3099-MONOMER
  val__L_c: 435591.18.peg.3870-MONOMER
braun's_lipoproteins: []
