growth_key: mu
START_tRNA: []
rna_components: []
feature_types:
- CDS
- rRNA
- tRNA
- ncRNA
- tmRNA
trna_misacylation: {}
knockouts: []
genome_mods: {}
peptide_release_factors:
  UAG: 556267.4.peg.489-MONOMER
  UGA: 556267.4.peg.1530-MONOMER
  UAA: generic_RF
complex_cofactors:
  fes_transfers:
  - CPLX_dummy
  fes_chaperones: {}
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_NiFe_cofactor_c: []
lipid_modifications: []
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- biomass525
- FMETTRS
- ATPM
ME-Model-ID: Helicobacter_winghamensis_ATCC_BAA_430-ME
m-model-path: ./me-models/Helicobacter_winghamensis_ATCC_BAA_430//building_data/m_model_modified.json
genbank-path: ./me-models/Helicobacter_winghamensis_ATCC_BAA_430//building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: ./me-models/Helicobacter_winghamensis_ATCC_BAA_430/Helicobacter_winghamensis_ATCC_BAA_430.xlsx
df_TranscriptionalUnits: ./me-models/Helicobacter_winghamensis_ATCC_BAA_430//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ''
df_matrix_subrxn_stoich: ''
df_metadata_orphan_rxns: ''
df_metadata_metabolites: ''
log_directory: ./me-models/Helicobacter_winghamensis_ATCC_BAA_430/
out_directory: ./me-models/Helicobacter_winghamensis_ATCC_BAA_430/
dev_reference: false
include_pseudo_genes: true
add_lipoproteins: false
estimate_keffs: true
blast_threads: 1
run_bbh_blast: false
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- 556267.4.peg.1327-MONOMER
- 556267.4.peg.486-MONOMER
other_lipids: []
default_sigma_factor: 556267.4.peg.670-MONOMER
rna_polymerases:
  RNAP_5562674peg434MONOMER:
    sigma_factor: 556267.4.peg.434-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_5562674peg670MONOMER:
    sigma_factor: 556267.4.peg.670-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
lipoprotein_precursors:
  AcrA: 556267.4.peg.11
  CusC: 556267.4.peg.9
  MetQ: 556267.4.peg.659
  MltC: 556267.4.peg.1574
ngam: 1.0
gam: 40.0
translocation_multipliers:
  556267.4.peg.42-MONOMER:
    556267.4.peg.1497: 2.0
amino_acid_trna_synthetase:
  ala__L_c: 556267.4.peg.1520-MONOMER
  arg__L_c: 556267.4.peg.627-MONOMER
  asn__L_c: CPLX_dummy
  asp__L_c: 556267.4.peg.946-MONOMER
  cys__L_c: 556267.4.peg.806-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: generic_glu_ligase
  gly_c: generic_gly_c_ligase
  his__L_c: CPLX_dummy
  ile__L_c: 556267.4.peg.525-MONOMER
  leu__L_c: 556267.4.peg.1594-MONOMER
  lys__L_c: 556267.4.peg.1191-MONOMER
  met__L_c: 556267.4.peg.830-MONOMER
  phe__L_c: generic_phe_ligase
  pro__L_c: 556267.4.peg.800-MONOMER
  ser__L_c: 556267.4.peg.1539-MONOMER
  thr__L_c: 556267.4.peg.165-MONOMER
  trp__L_c: 556267.4.peg.1290-MONOMER
  tyr__L_c: 556267.4.peg.736-MONOMER
  val__L_c: 556267.4.peg.1108-MONOMER
braun's_lipoproteins: []
